version: "3"
services:
  main:
    container_name: app
    build:
      context: .
      target: development
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 3600:3600
    env_file:
      - .env
    networks:
      - postgres
  postgres:
    container_name: best-playz
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres
  pgadmin:
    links:
      - postgres:postgres
    container_name: best-playz-pgadmin
    image: dpage/pgadmin4
    ports:
      - "8083:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
